# Project - Topological Data Analysis   

In [50]:
# import packages
from sklearn.datasets import load_iris
from gtda.diagrams import PersistenceLandscape
from gtda.diagrams import PersistenceImage
from gtda.homology import VietorisRipsPersistence
from gtda.diagrams import BettiCurve, PersistenceLandscape, PairwiseDistance, PersistenceEntropy
from gtda.plotting import plot_point_cloud

In [34]:
# load iris dataset 
x, y = load_iris(return_X_y = True)
print("X: ", x[:10])
print("Y: ", y[:10])

X:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
Y:  [0 0 0 0 0 0 0 0 0 0]


In [35]:
print(x.shape)

(150, 4)


In [27]:
# plot cloud of points for columns 0 and 1 
plot_point_cloud(x[:, :2])

In [28]:
plot_point_cloud(x[:, 2:])

Persistence diagram of the Vietoris-Rips complex

for 2 dimensions of Iris dataset

In [41]:
xa = x[:, :2]
xa = xa.reshape(1, *xa.shape)

In [44]:
xa.shape

(1, 150, 2)

In [45]:
vr = VietorisRipsPersistence()
xt = vr.fit_transform(xa)
vr.plot(xt)


For all 4 dimensions of Iris dataset

In [48]:
xp = x.reshape(1, *x.shape)
xp.shape

(1, 150, 4)

In [49]:
vr = VietorisRipsPersistence()
xt = vr.fit_transform(xp)
vr.plot(xp)

Betti Curve

In [52]:
bc = BettiCurve()
x_betti_curve = bc.fit_transform_plot(xt)

Landscape persistence

In [53]:
pl = PersistenceLandscape()
x_presistence_landscape = pl.fit_transform_plot(xt)

Compute bottleneck and wasserstein distances