# Project - Topological Data Analysis   
version 1.0

In [1]:
# import packages
from sklearn.datasets import load_iris
from gtda.diagrams import PersistenceLandscape
from gtda.diagrams import PersistenceImage
from gtda.homology import VietorisRipsPersistence
from gtda.diagrams import BettiCurve, PersistenceLandscape, PairwiseDistance, PersistenceEntropy
from gtda.plotting import plot_point_cloud

In [32]:
# load iris dataset 
x, y = load_iris(return_X_y = True)
print("X: ", x[:10])
print("Y: ", y[:10])

X:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
Y:  [0 0 0 0 0 0 0 0 0 0]


In [3]:
print(x.shape)

(150, 4)


In [4]:
# plot cloud of points for columns 0 and 1 
plot_point_cloud(x[:, :2])

In [5]:
plot_point_cloud(x[:, 2:])

Persistence diagram of the Vietoris-Rips complex

for 2 dimensions of Iris dataset

In [6]:
xa = x[:, :2]
xa = xa.reshape(1, *xa.shape)

In [7]:
xa.shape

(1, 150, 2)

In [8]:
vr = VietorisRipsPersistence()
xt = vr.fit_transform(xa)
vr.plot(xt)


For all 4 dimensions of Iris dataset

In [9]:
# reshape the dimensions of dataset
xp = x.reshape(1, *x.shape)
xp.shape

(1, 150, 4)

In [10]:
# build Vietoris Rips Persistence diagram for 4 dimensions
# calculation of persistence homology
vr = VietorisRipsPersistence()
xt = vr.fit_transform(xp)
vr.plot(xt)

Betti Curve

In [11]:
# build Betti Curve
bc = BettiCurve()
x_betti_curve = bc.fit_transform_plot(xt)

Landscape persistence

In [13]:
# build persistence landscape
pl = PersistenceLandscape()
x_presistence_landscape = pl.fit_transform_plot(xt)

Compute bottleneck and wasserstein distances

In [45]:
# bottleneck distance
def compute_bottleneck_distance(diag1, diag2):
    bottleneck_distance = gd.bottleneck_distance(diag1, diag2)
    return bottleneck_distance

In [46]:
# wasserstein distance
def compute_wasserstein_distance(diag1, diag2):
    wasserstein_distance = gd.wasserstein_distance(diag1, diag2)
    return wasserstein_distance

Classification task using average persistence landscape

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC 


In [34]:
# check the dimensionality of the data
print("dim-input = ", x.shape)
print("dim-output = ", y.shape)

dim-input =  (150, 4)
dim-output =  (150,)


In [36]:
# normalization of data
scaler = StandardScaler()
x = scaler.fit_transform(x)
print(x.shape)

(150, 4)


In [37]:
x2 = x.reshape(1, *x.shape)
print(x2.shape)

(1, 150, 4)


In [38]:
# compute persistence diagrams
rieps_complex = VietorisRipsPersistence()
diagrams = rieps_complex.fit_transform(x2)

In [39]:
rieps_complex.plot(diagrams)

In [40]:
landscape = PersistenceLandscape()
landscapes = landscape.fit_transform(diagrams)

In [41]:
landscape.plot(landscapes)

In [30]:
x = x.reshape()
x.shape

(600,)

In [42]:
# split dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 1, test_size = 0.3)

In [43]:
# for train-set

# compute persistence homology
rieps_train = VietorisRipsPersistence()
diagram_train = rieps_complex.fit_transform(x_train.reshape(1, *x_train.shape))

#compute
landscape_train = PersistenceLandscape()
landscape_train = landscape_train.fit_transform(diagram_train)

In [44]:
# train process 
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(landscape_train, y_train)

ValueError: Found array with dim 3. Estimator expected <= 2.

In [ ]:
# for test-set

# compute persistence homology
rieps_train = VietorisRipsPersistence()
diagram_train = rieps_complex.fit_transform(x_train.reshape(1, *x_train.shape))

#compute
landscape_train = PersistenceLandscape()
landscape_train = landscape_train.fit_transform(diagram_train)

In [ ]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit()